logLevel: "INFO"
showFooter: false
showNavigation: true
enableCustomJs: true
sectionNavigationStyle: topbar
themeName: CatppuccinMocha
pageTitle: SuriCorp

actions:
  - title: Update container entity file
    shell: docker ps -a --filter "name=All-The-Mods-9" --filter "name=JDownloader2" --format json > /config/entities/container.json
    hidden: true
    execOnStartup: true
    execOnCron: '*/5 * * * *'
    
  - title: Start {{ container.ID }}
    icon: <iconify-icon icon="tabler:play"></iconify-icon>
    shell: docker start {{ container.Names }}
    entity: container
    trigger: Update container entity file

  - title: Stop {{ container.ID }}
    icon: <iconify-icon icon="mingcute:stop-line"></iconify-icon>
    shell: docker stop {{ container.Names }}
    timeout: 8
    entity: container
    trigger: Update container entity file
    
  - title: Restart {{ container.ID }}
    icon: <iconify-icon icon="mdi:restart"></iconify-icon>
    shell: docker restart {{ container.Names }}
    entity: container
    trigger: Update container entity file
    
  - title: View logs {{ container.ID }}
    popupOnStart: execution-dialog-stdout-only
    icon: <iconify-icon icon="tabler:logs"></iconify-icon>
    shell: docker logs --tail 100 -f {{ container.Names }}
    timeout: 100
    entity: container

# Docs: http://docs.olivetin.app/entities.html
entities:
  - file: /config/entities/container.json
    name: container

# The only way to properly use entities, are to use them with a `fieldset` on a dashboard.
dashboards:
  - title: Containers
    contents:
      - title: |
          Container {{ container.Names }}
          Image Source: {{ container.Image }}
        entity: container
        type: fieldset
        contents:
          - type: display
            title: |
              <h1>Status</h1>
              <p class="{{ container.State }}">{{ container.Status }}</p>
          - title: 'Start {{ container.ID }}'
            cssClass: '{{ container.State }}'
          - title: 'Stop {{ container.ID }}'
            cssClass: '{{ container.State }}'
          - title: 'Restart {{ container.ID }}'
            cssClass: '{{ container.State }}'
          - title: 'View logs {{ container.ID }}'
            cssClass: '{{ container.State }}'